//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchResumenEjecutivo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_AuditoriaDetalle
    {
        public int AuditoriaDetalleID { get; set; }
        public int AuditoriaID { get; set; }
        public string Campo { get; set; }
        public string ValorAnterior { get; set; }
        public string ValorActual { get; set; }
    
        public virtual PC_Auditoria PC_Auditoria { get; set; }
    }
}
