//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchResumenEjecutivo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_Auditoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PC_Auditoria()
        {
            this.PC_AuditoriaDetalle = new HashSet<PC_AuditoriaDetalle>();
        }
    
        public int AuditoriaID { get; set; }
        public string Aplicacion { get; set; }
        public string Proceso { get; set; }
        public string Detalle { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PC_AuditoriaDetalle> PC_AuditoriaDetalle { get; set; }
    }
}
