//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchResumenEjecutivo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC_PermisoUsuario
    {
        public int IDPermiso { get; set; }
        public int IDUsuario { get; set; }
        public int IDCorredor { get; set; }
    
        public virtual PC_Permiso PC_Permiso { get; set; }
        public virtual PC_Usuario PC_Usuario { get; set; }
    }
}
